### PR TITLE
new datastore - s3

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/worker/7)

### CODE REVIEW

**Comment by yehiyam** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/consumer/JobConsumer.js, line 137 at r1](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L4pGQ2fEkXoy0NrKdao:-L4pGQ2fEkXoy0NrKdap:bdrp4nx) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/consumer/JobConsumer.js#L137)):*
> ```JavaScript
>         });
>         await etcd.update({
>             jobId: this._job.data.jobID, taskId: this._job.data.taskID, status, result: { pipelineId: this._job.data.jobID, taskId: this._job.data.taskID }, error
> ```

Add adapter name to result object

---

*[lib/datastore/adapters/s3-adapter.js, line 1 at r1](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L4pGnJsH6AzFcYVspp0:-L4pGnJsH6AzFcYVspp1:bhacgmh) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/datastore/adapters/s3-adapter.js#L1)):*
> ```JavaScript
> 
> ```

1. Move to npm package
2. Add get method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/worker/7)*

**Comment by yehiyam** [comment]
Reviewed 3 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/worker/7)*

**Comment by bahalool** [comment]
fixed !

**Comment by yehiyam** [comment]
Reviewed 1 of 7 files at r1, 1 of 5 files at r2, 4 of 10 files at r3, 2 of 5 files at r5, 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[lib/worker.js, line 84 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lF6SFkLs7S9WMBsue:-L6lF6SFkLs7S9WMBsuf:b-xtxpq3) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/worker.js#L84)):*
> ```JavaScript
>                     break;
>                 case workerStates.init:
>                     await jobConsumer.initJob();
> ```

check that there is a try-catch someware

---

*[lib/consumer/data-extractor.js, line 33 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lEGERGsc6dAXKMSvz:-L6lEGERGsc6dAXKMSw-:b-amn99j) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/data-extractor.js#L33)):*
> ```JavaScript
>     }
> 
>     _flatObject(input) {
> ```

try to find a well known function that does that

---

*[lib/consumer/JobConsumer.js, line 137 at r1](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L4pGQ2fEkXoy0NrKdao:-L6lQ3qZhIBhYSnLpVwf:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/consumer/JobConsumer.js#L137)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Add adapter name to result object
</blockquote></details>

Done.

---

*[lib/consumer/JobConsumer.js, line 170 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lGfnv3GQf2YvJNNSM:-L6lGfnv3GQf2YvJNNSN:bt0ffgx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L170)):*
> ```JavaScript
>         }
>         catch (err) {
>             log.error('failed to extract data input', this._jobID, err);
> ```

log.error according to convention

---

*[lib/consumer/JobConsumer.js, line 215 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lPhg0aUzpwDjDABwf:-L6lPhg0aUzpwDjDABwg:blrlyk1) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L215)):*
> ```JavaScript
>     }
> 
>     async _putResult(status, resultData) {
> ```

return new status, and change the original status in the caller

---

*[lib/consumer/JobConsumer.js, line 217 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lHb_-Q1YJSiMGgHnI:-L6lHb_-Q1YJSiMGgHnJ:b-63t07g) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L217)):*
> succeed
change to consts

---

*[test/consumerTest.js, line 10 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lCdCqKhdzPb6YqI5S:-L6lCdCqKhdzPb6YqI5T:b-yj27sf) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L10)):*
> ```JavaScript
> const worker = require('../lib/worker');
> const jobID = 'test-jobID-3232dd-124fdg4-sdffs234-cs3424';
> const taskID = 'test-taskID-123123-123123123-123123123-123';
> ```

generate new GUID 

---

*[test/consumerTest.js, line 123 at r7](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L6lCJSOtvW5qR2mKBgv:-L6lCJSOtvW5qR2mKBgw:b-5swlhn) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L123)):*
> ```JavaScript
>     });
> 
>     it('should get job', (done) => {
> ```

should get job should also test that the input was read correctly

---

*[lib/datastore/adapters/s3-adapter.js, line 1 at r1](https://reviewable.io:443/reviews/kube-hpc/worker/7#-L4pGnJsH6AzFcYVspp0:-L6lQ1y2qGX_wmsd73wB:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/datastore/adapters/s3-adapter.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

1. Move to npm package
2. Add get method

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/worker/7)*

**Comment by yehiyam** [comment]
Reviewed 8 of 8 files at r8.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[lib/worker.js, line 84 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lF6SFkLs7S9WMBsue:-L6w4FqH4Cvd1x3889Pg:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/worker.js#L84)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

check that there is a try-catch someware
</blockquote></details>

Done.

---

*[lib/consumer/data-extractor.js, line 33 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lEGERGsc6dAXKMSvz:-L6w4JxxC42SkgMKKIAF:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/data-extractor.js#L33)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

try to find a well known function that does that
</blockquote></details>

Done.

---

*[lib/consumer/JobConsumer.js, line 170 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lGfnv3GQf2YvJNNSM:-L6w4Pm60jCdvmy2Bnvo:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L170)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

log.error according to convention
</blockquote></details>

Done.

---

*[lib/consumer/JobConsumer.js, line 215 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lPhg0aUzpwDjDABwf:-L6w4XSz0sbnMDl5wfcI:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L215)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

return new status, and change the original status in the caller
</blockquote></details>

Done.

---

*[lib/consumer/JobConsumer.js, line 217 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lHb_-Q1YJSiMGgHnI:-L6w4Z4S0fcr9Wp6hFZM:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L217)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> succeed
change to consts
</blockquote></details>

Done.

---

*[test/consumerTest.js, line 10 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lCdCqKhdzPb6YqI5S:-L6w4jBC6mZ06TX_kqFK:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

generate new GUID 
</blockquote></details>

Done.

---

*[test/consumerTest.js, line 123 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lCJSOtvW5qR2mKBgv:-L6w4lOx5Gm1TYYYDldK:b-896fix) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L123)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

should get job should also test that the input was read correctly
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kube-hpc/worker/7)*

**Comment by yehiyam** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[lib/worker.js, line 84 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lF6SFkLs7S9WMBsue:-L6w5CDxAMvWyKU6_nnK:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/worker.js#L84)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[lib/consumer/data-extractor.js, line 33 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lEGERGsc6dAXKMSvz:-L6w5CyR1AlZYFEq_9bj:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/data-extractor.js#L33)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[lib/consumer/JobConsumer.js, line 137 at r1](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L4pGQ2fEkXoy0NrKdao:-L6w51X02tEFvKYJzym1:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/consumer/JobConsumer.js#L137)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[lib/consumer/JobConsumer.js, line 170 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lGfnv3GQf2YvJNNSM:-L6w5Dsa1Q0P3QT0wjc_:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L170)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[lib/consumer/JobConsumer.js, line 215 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lPhg0aUzpwDjDABwf:-L6w552B8ykJn8AUTW-Z:b-wj3f01) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L215)):*
> LGTM

---

*[lib/consumer/JobConsumer.js, line 217 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lHb_-Q1YJSiMGgHnI:-L6w563O39C4It9ahiWw:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/lib/consumer/JobConsumer.js#L217)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[test/consumerTest.js, line 10 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lCdCqKhdzPb6YqI5S:-L6w59VX1nyEHGYei0Ij:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[test/consumerTest.js, line 123 at r7](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L6lCJSOtvW5qR2mKBgv:-L6w5ASwCDPQTtQqCtH_:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/b3ab8730e22a27f341958b4b2bfc55453329de57/test/consumerTest.js#L123)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[lib/datastore/adapters/s3-adapter.js, line 1 at r1](https://beta.reviewable.io/reviews/kube-hpc/worker/7#-L4pGnJsH6AzFcYVspp0:-L6w5BO23NH9CrhPQJqq:bb6ywmx) ([raw file](https://github.com/kube-hpc/worker/blob/ea6a0f652f9a0d709310b6d18ab5e31d10ef2458/lib/datastore/adapters/s3-adapter.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/kube-hpc/worker/7)*

**Comment by yehiyam** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kube-hpc/worker/7)*

**Pull request merged**
